## Unsupervised Learning: Clustering

What problem does clustering solve?
Say for example with knew there were 3 types of iris but we did not label them in the dataset. We could try clustering them in order to separate the iris based on their type. "Clustering is a way to split observations into well-separated groups called clusters"

https://scikit-learn.org/stable/tutorial/statistical_inference/unsupervised_learning.html

In [24]:
#K means clustering
import numpy as np
from sklearn import cluster, datasets
X_iris, y_iris = datasets.load_iris(return_X_y = True)

In [18]:
k_means = cluster.KMeans(n_clusters = 3)
k_means.fit(X_iris)#clustering will apply labels to data. We can separate data with these labels

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=3, n_init=10, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [17]:
print(k_means.labels_[::10])#we want a label every 10 labels
print(y_iris[::10])
# Extended slices: https://docs.python.org/release/2.3.5/whatsnew/section-slices.html
    #Could be useful for getting a well distributed sample

[1 1 1 1 1 0 0 0 0 0 2 2 2 2 2]
[0 0 0 0 0 1 1 1 1 1 2 2 2 2 2]


In [6]:
k_means.labels_

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1])

In [28]:
#feature agglomeration???
from sklearn.feature_extraction import grid_to_graph

In [27]:
digits = datasets.load_digits()
images = digits.images
X = np.reshape(images, (len(images), -1))
connectivity = grid_to_graph(*images[0].shape)

agglo = cluster.FeatureAgglomeration(connectivity=connectivity,
                                     n_clusters=32)
agglo.fit(X)

X_reduced = agglo.transform(X)

X_approx = agglo.inverse_transform(X_reduced)
images_approx = np.reshape(X_approx, images.shape)